# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-mfa-go" do
  name "aws-mfa-go"
  desc "Minimal AWS MFA helper for the CLI (STS GetSessionToken -> ~/.aws/credentials)"
  homepage "https://github.com/jlis/aws-mfa-go"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-mfa-go"

  on_macos do
    on_intel do
      url "https://github.com/jlis/aws-mfa-go/releases/download/v#{version}/aws-mfa-go_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/jlis/aws-mfa-go"
      sha256 "ea0f946eacac7640466165162263c172c10cc6328e1454c78a52e68b51d2b11d"
    end
    on_arm do
      url "https://github.com/jlis/aws-mfa-go/releases/download/v#{version}/aws-mfa-go_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/jlis/aws-mfa-go"
      sha256 "a72608c52dbb6b3e58aceb99ad9d3f018ea13a743da1c97841870ee0d18a8938"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jlis/aws-mfa-go/releases/download/v#{version}/aws-mfa-go_#{version}_linux_amd64.tar.gz",
        verified: "github.com/jlis/aws-mfa-go"
      sha256 "946250ea8b1eaf0d9b21aae4964af1bcc54417ea1d5ee62c7fef8a19628d8537"
    end
    on_arm do
      url "https://github.com/jlis/aws-mfa-go/releases/download/v#{version}/aws-mfa-go_#{version}_linux_arm64.tar.gz",
        verified: "github.com/jlis/aws-mfa-go"
      sha256 "4381f76004a5de33cdc982874e7da0e4f6515ec28980e58bbc6fe0209f15d715"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aws-mfa-go"]
    end
  end

  # No zap stanza required
end
