# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-mfa-go" do
  name "aws-mfa-go"
  desc "Minimal AWS MFA helper for the CLI (STS GetSessionToken -> ~/.aws/credentials)"
  homepage "https://github.com/jlis/aws-mfa-go"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-mfa-go"

  on_macos do
    on_intel do
      url "https://github.com/jlis/aws-mfa-go/releases/download/v#{version}/aws-mfa-go_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/jlis/aws-mfa-go"
      sha256 "edeb57e97ac8e67046bed9622cc962fa46b79a475955d6247bc2b2a5b8365d1a"
    end
    on_arm do
      url "https://github.com/jlis/aws-mfa-go/releases/download/v#{version}/aws-mfa-go_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/jlis/aws-mfa-go"
      sha256 "4082483b5cb7a6ce11cd26c78bd96f5d7edaed72424d929e774bf6b845367e5f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jlis/aws-mfa-go/releases/download/v#{version}/aws-mfa-go_#{version}_linux_amd64.tar.gz",
        verified: "github.com/jlis/aws-mfa-go"
      sha256 "9378f2a6edab22ac3a7b96ed2944fcaedf27bae73748bfe812054b29e9dbdffa"
    end
    on_arm do
      url "https://github.com/jlis/aws-mfa-go/releases/download/v#{version}/aws-mfa-go_#{version}_linux_arm64.tar.gz",
        verified: "github.com/jlis/aws-mfa-go"
      sha256 "f5d879e235cdd14672e1c71e1b586d1ad2d1ba43291f47184687815a6d034af2"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aws-mfa-go"]
    end
  end

  # No zap stanza required
end
