# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-mfa-go" do
  name "aws-mfa-go"
  desc "Minimal AWS MFA helper for the CLI (STS GetSessionToken -> ~/.aws/credentials)"
  homepage "https://github.com/jlis/aws-mfa-go"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-mfa-go"

  on_macos do
    on_intel do
      url "https://github.com/jlis/aws-mfa-go/releases/download/v#{version}/aws-mfa-go_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/jlis/aws-mfa-go"
      sha256 "befccf6fc802753433a213e9f722015853cdb3ee2424192557d9711a095381a8"
    end
    on_arm do
      url "https://github.com/jlis/aws-mfa-go/releases/download/v#{version}/aws-mfa-go_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/jlis/aws-mfa-go"
      sha256 "8757e22c1262b28d26942432f9a986ead4032dd82d5ff8ecfbde33fe039525a9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jlis/aws-mfa-go/releases/download/v#{version}/aws-mfa-go_#{version}_linux_amd64.tar.gz",
        verified: "github.com/jlis/aws-mfa-go"
      sha256 "62c7ebf6243396b9ee3f00498ab5ee3dba09fc970b1e114bc7ccd0265e3ed7c9"
    end
    on_arm do
      url "https://github.com/jlis/aws-mfa-go/releases/download/v#{version}/aws-mfa-go_#{version}_linux_arm64.tar.gz",
        verified: "github.com/jlis/aws-mfa-go"
      sha256 "8e60fd194c57f8493bcfbed22e8209bd4d6fb19254320c0c913d0d470a9da42c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aws-mfa-go"]
    end
  end

  # No zap stanza required
end
